### ISSUE TITLE
[TIL] 2025-01-21 (화)

### ISSUE THREAD

**Issue by banban-jpg** [banban-jpg/TIL#3]
# 2025-01-21 화 수업 4일차 (47명)

### - 7/19일 기준 노션 공유 끊김
  - 노션 링크를 활용해서 본인 교제로 활용
  - 블로그, 회고록 제작 추천
### - 전날 수업 복습은 VS Code에서 작성

---

### **TIL을 위한 이모지 모음 사이트**
- [https://emojipedia.org/](https://emojipedia.org/)

### **HTML 관련 사이트**
- [https://www.w3schools.com/](https://www.w3schools.com/)

### **웹 공부 관련 사이트**
- [https://poiemaweb.com/](https://poiemaweb.com/)

### **온라인 책 관련 서치 사이트**
- [https://wikidocs.net/](https://wikidocs.net/)

### **UX 관련 사이트**
- [https://upa.userspoon.com/?uxPatternIds=99999](https://upa.userspoon.com/?uxPatternIds=99999)

### **디자인 용어 사전**
- [https://designbase.co.kr/dictionary_categories/ui/](https://designbase.co.kr/dictionary_categories/ui/)

### **모바일 UI 사이트 관련 사이트**
- [https://wwit.design/](https://wwit.design/)

### **UI 관련 사이트**
- [https://uibowl.io/](https://uibowl.io/)

### **국내 데스크탑 UI 수상작 사이트**
- [https://gdweb.co.kr/main/](https://gdweb.co.kr/main/)

### **해외 데스크탑 UI 사이트**
- 이프 디자인

### **개발/기술/스타트업 뉴스 사이트**
- [news.hada.io](https://news.hada.io)

### **무료 강의 모음집**
- [https://www.boostcourse.org/opencourse](https://www.boostcourse.org/opencourse)
  - 모두를 위한 컴퓨터 과학 (CS50 2019)

### **강의 모음집 2**
- [https://www.kmooc.kr/view/course](https://www.kmooc.kr/view/course)

### **페비콘 사이트**
- [https://realfavicongenerator.net/](https://realfavicongenerator.net/)

### **무료 이미지 사진**
- [https://unsplash.com/ko](https://unsplash.com/ko)

### **웹 폰트 스타일/사이즈 체크**
- [https://fonts.google.com/?lang=ko_Kore&preview.size=78](https://fonts.google.com/?lang=ko_Kore&preview.size=78)

---

### **새로운 사이트들**
- 부트스트랩: [https://getbootstrap.com/](https://getbootstrap.com/)
- 색조합 1: [https://colorhunt.co/](https://colorhunt.co/)
- 색조합 2: [https://2colors.colorion.co/](https://2colors.colorion.co/)
- 색조합 3: [https://aicolors.co/](https://aicolors.co/)

---

### **찾아봐야 할 단어 목록**
- **GTD**
- **PARA**

---

### **복습**
- VS Code 일자별 HTML 참고

---

### 1. Static
- 요소의 기본 위치 지정 방식
- 문서의 일반적인 흐름을 따름
- 아무것도 변경하지 않았다를 표현할 때 사용함(디폴트 값)

### 2. Relative
- 본인을 기준으로 생각하게 함
- 새로운 기준이 되어주기도 함
- 마우스 스크롤의 영향을 받는다.

### 3. Absolute
- 요소를 일반적인 문서 흐름에서 제거하고, 가장 가까운 위치 지정 조상 요소(static이 아닌 조상)를 기준으로 배치
- 조상 중 위치 지정 요소가 없다면 초기 컨테이닝 블록(보통)을 기준으로 함

### 4. Fixed
- 문서 흐름에서 제거하고, 뷰포트(브라우저 창)를 기준으로 고정 위치에 배치
- 스크롤해도 같은 위치에 있음
- top, right, bottom, left로 위치 지정

### 5. Sticky
- 요소를 일반적인 문서 흐름에 따라 배치하다가, 지정된 임계점(threshold)에 도달하면 fixed처럼 동작
- 스크롤 위치가 임계점을 넘어가면 요소가 화면에 고정
- 부모 컨테이너 내에서만 고정

### 6. z-index
- 요소의 쌓임 순서(stacking order)를 제어
- 높은 값을 가진 요소가 낮은 값을 가진 요소 위에 표시
- position 값이 static이 아닌 요소에만 적용

---

## **Flex**

- 공간 배분과 정렬 기능을 제공하는 1차원적 레이아웃 모델
- 행, 열 단위로 작성

### **Flexbox의 장점**
- 레이아웃 간단하게 구현
- 동적인 경우에 유리함
- 정렬, 균등하게 분배가 쉬움
- 반응형 디자인에 유리
- 코드의 간결함

---

### 1. **display: flex**
- **설명**: Flexbox 컨테이너를 설정하는 속성입니다.
- **예시**:
    ```css
    .container {
      display: flex;
    }
    ```

### 2. **flex-direction**
- **설명**: 항목들의 배치 방향을 설정합니다. 기본값은 `row`입니다.
    - `row`: 가로 방향
    - `column`: 세로 방향
- **예시**:
    ```css
    .container {
      display: flex;
      flex-direction: column;
    }
    ```

### 3. **justify-content**
- **설명**: 주축(main axis)을 따라 항목들을 어떻게 정렬할지 결정합니다.
    - `flex-start`: 시작 부분에 배치
    - `center`: 중앙에 배치
    - `space-between`: 항목들 간에 동일한 간격
- **예시**:
    ```css
    .container {
      display: flex;
      justify-content: center;
    }
    ```

### 4. **align-items**
- **설명**: 교차 축(cross axis)에서 항목들의 정렬 방식을 결정합니다.
    - `flex-start`: 교차 축의 시작 부분에 배치
    - `center`: 교차 축의 중앙에 배치
    - `stretch`: 항목들을 교차 축을 따라 늘림
- **예시**:
    ```css
    .container {
      display: flex;
      align-items: center;
    }
    ```

### 5. **flex-wrap**
- **설명**: 항목들이 한 줄에 다 들어가지 않으면 어떻게 처리할지를 결정합니다.
    - `nowrap`: 한 줄에 배치
    - `wrap`: 여러 줄로 나눠 배치
- **예시**:
    ```css
    .container {
      display: flex;
      flex-wrap: wrap;
    }
    ```

### 6. **flex-grow**
- **설명**: 항목이 남은 공간을 얼마나 차지할지 결정합니다.
    - `1`: 남은 공간을 고르게 차지
- **예시**:
    ```css
    .item {
      flex-grow: 1;
    }
    ```

### 7. **flex-shrink**
- **설명**: 항목이 부족한 공간에서 얼마나 축소될지 설정합니다.
    - `1`: 공간이 부족하면 축소됨
- **예시**:
    ```css
    .item {
      flex-shrink: 1;
    }
    ```

### 8. **flex-basis**
- **설명**: 항목의 **기본 크기**를 설정합니다. 이 값은 `flex-grow`와 `flex-shrink`가 적용되기 전의 항목 크기입니다.
    - `200px`: 기본 크기를 200px로 설정
- **예시**:
    ```css
    .item {
      flex-basis: 200px;
    }
    ```

### 9. **flex**
- **설명**: `flex-grow`, `flex-shrink`, `flex-basis`를 한 번에 설정하는 속성입니다.
    - 예: `flex: 1 1 200px;`
- **예시**:
    ```css
    .item {
      flex: 1 1 200px;
    }
    ```

### 10. **gap**
- **설명**: 항목들 간의 간격을 설정합니다. `margin`을 따로 설정할 필요 없이 항목 사이의 간격을 일관되게 유지할 수 있습니다.
- **예시**:
    ```css
    .container {
      display: flex;
      gap: 20px;
    }
    ```

---

## **FLEXBOX FROGGY**

Flex에 적응하기 위한 게임 사이트: [flexboxfroggy.com/#ko](https://flexboxfroggy.com/#ko)

---

### **사용 예시**

```html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Flexbox 예제</title>
  <style>
    .container {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-wrap: wrap;
      gap: 20px;
      height: 100vh;
    }

    .item {
      flex: 1 1 200px;
      background-color: #4CAF50;
      padding: 20px;
      color: white;
      text-align: center;
      margin: 10px;
    }
  </style>
</head>
<body>

  <div class="container">
    <div class="item">항목 1</div>
    <div class="item">항목 2</div>
    <div class="item">항목 3</div>
    <div class="item">항목 4</div>
  </div>

</body>
</html>

```

---

## flex-direction, justify-content, align-items 차이점
- flex-direction: 요소들의 배치 방향을 설정합니다. (가로 또는 세로 방향)
- justify-content: **주축(main axis)**을 따라 항목들의 간격을 설정합니다.
- align-items: **교차 축(cross axis)**을 따라 항목들을 정렬합니다.

### 단순 정렬로 이해하면 안 되는 이유:
- justify-content는 주축을, align-items는 교차 축을 기준으로 정렬합니다. 두 속성이 다른 축을 기준으로 동작하므로, 각각의 축에 대해 정확히 이해하고 사용해야 합니다.

### 결론:

- flex-direction: 배치 방향
- justify-content: 주축 기준 간격
- align-items: 교차 축 기준 정렬

---

### Reset CSS
- 브라우저 간 기본 스타일 차이를 없애고 일관된 스타일 제공을 위해 사용함
- 브라우저마다 스타일링이 다르므로 처음부터 스타일을 정할 수 있게 도와줌
- 디자인에 신경 쓸 시간을 줄이고, 콘텐츠나 기능에 더 집중할 수 있다.

### 대표적인 Reset:

- Eric Meyer, Reset CSS
- HTML5 Doctor, Reset

### Bootstrap이란

-  **CSS 프레임워크(CSS Framework)**는 웹사이트의 스타일링 작업을 간편하게 만들어주는 도구 모음
- 일반적으로 레이아웃, 디자인 구성 요소, 반응형 디자인 등의 기능을 제공하며, 개발자는 이를 활용해 시간과 노력을 절약할 수 있음
- 주요 CSS 프레임워크로는 Bootstrap, Foundation, Bulma, Tailwind 등이 있음
- 코드 재사용성 증가
- 반응형 디자인 지원
- 개발 시간 단축
- 크로스 브라우저 호환성 개선
 
### CDN을 통한 설치

```html
<!-- CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<!-- JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
```

### 컨테이너 (Container)

- 페이지의 내용이 자동으로 정렬되고 반응형으로 동작하도록 돕는 레이아웃의 기본 틀을 제공
- container: 고정된 너비의 레이아웃
- container-fluid: 화면 크기에 맞춰 100% 너비로 늘어나는 레이아웃
### 그리드 시스템 (Grid System)

- 페이지를 12개의 열로 나누어 레이아웃을 설정할 수 있게 해줌

### 컴포넌트 (Components)

- 미리 디자인된 다양한 UI 요소들 (버튼, 네비게이션 바, 카드 등)
